version: "3.8"
services:
  nginx:
    build: ./.build/nginx
    ports:
      - 80:80
    volumes:
      - .build/nginx/nginx:/etc/nginx
    volumes_from:
      - "php:ro"
    depends_on:
      - php
    networks:
      - internal
  php:
    build:
      context: ./.build/php
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./:/app
      - ~/.ssh:/var/www/.ssh
    environment:
      XDEBUG_CONFIG: "client_host=192.168.220.1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      TZ: Europe/Moscow
      POSTGRES_PASSWORD: init-localhost
      POSTGRES_USER: init-localhost
      POSTGRES_DB: init-localhost
    networks:
      - internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
volumes:
  data: